name: PR label gates

on:
  pull_request:
    types: [labeled]

jobs:
  set-env:
    uses: astognev-org/devops/.github/workflows/set-env.yml@main
    with:
      GHCR_DOCKER_REGISTRY_PATH: ghcr.io/${{ github.repository }}

  labels:
    needs: set-env
    uses: astognev-org/devops/.github/workflows/labels_devops.yml@main
    with:
      verify_enabled: ${{ contains(github.event.label.name, 'verify') }}
      publish_enabled: ${{ contains(github.event.label.name, 'publish') }}
      base_ref: ${{ github.event.pull_request.base.ref }}
      head_sha: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.event.pull_request.number }}
      # image_ref: ghcr.io/${{ github.repository }}:${{ github.event.pull_request.head.sha }}
      image_ref: ${{ needs.set-env.outputs.DOCKER_IMAGE_NAME }}
    permissions:
      contents: write
      pull-requests: read
      packages: read
