name: PR label gates

on:
  pull_request:
    types: [labeled]

jobs:
  set-env:
    uses: astognev-org/devops/.github/workflows/set-env.yml@main
    with:
      GHCR_DOCKER_REGISTRY_PATH: ghcr.io/${{ github.repository }}

  labels:
    needs: set-env
    uses: astognev-org/devops/.github/workflows/labels_devops.yml@main
    with:
      verify_enabled: ${{ contains(github.event.label.name, 'verify') }}
      publish_enabled: ${{ contains(github.event.label.name, 'publish') }}
      VERSION: ${{ needs.set-env.outputs.VERSION }}
      PR_BASE_REF: ${{ needs.set-env.outputs.PR_BASE_REF }}
      PR_SHA: ${{ needs.set-env.outputs.PR_SHA }}
      PR_NUMBER: ${{ needs.set-env.outputs.PR_NUMBER }}
      DOCKER_IMAGE_NAME: ${{ needs.set-env.outputs.DOCKER_IMAGE_NAME }}
    permissions:
      contents: write
      pull-requests: read
      packages: read
